# Serves for configuration of CodeClimate (automated code review for test coverage, complexity, duplication, etc.)
version: "2"
plugins:
  structure:
    enabled: true
    exclude_patterns:
      - "**/migrations/"
      - "**/tests/"
      - "**/tests.py"
      - "askup/static/admin"
      - "askup/static/debug_toolbar"
      - ".tox/"
      - ".eggs/"
      - ".dc-*/"
  radon:
    enabled: true
    exclude_patterns:
      - "**/migrations/"
      - "**/tests/"
      - "**/tests.py"
      - "askup/static/admin"
      - "askup/static/debug_toolbar"
      - ".tox/"
      - ".eggs/"
      - ".dc-*/"
    config:
      python_version: 3
      threshold: "C"
  fixme:
    enabled: true
    exclude_patterns:
      - "**/migrations/"
      - "**/tests/"
      - "**/tests.py"
      - "askup/static/admin"
      - "askup/static/debug_toolbar"
      - ".tox/"
      - ".eggs/"
      - ".dc-*/"
    config:
      strings:
        - BUG
        - FIXME
  duplication:
    enabled: true
    exclude_patterns:
      - "**/migrations/"
      - "**/tests/"
      - "**/tests.py"
      - "askup/static/admin"
      - "askup/static/debug_toolbar"
      - ".tox/"
      - ".eggs/"
      - ".dc-*/"
    config:
      languages:
        - javascript:
        - python:
            python_version: 3
  eslint:
    enabled: true
    exclude_patterns:
      - "**/migrations/"
      - "**/tests/"
      - "**/tests.py"
      - "askup/static/admin"
      - "askup/static/debug_toolbar"
      - ".tox/"
      - ".eggs/"
      - ".dc-*/"
  markdownlint:
    enabled: true
    exclude_patterns:
      - "**/migrations/"
      - "**/tests/"
      - "**/tests.py"
      - "askup/static/admin"
      - "askup/static/debug_toolbar"
      - ".tox/"
      - ".eggs/"
      - ".dc-*/"

checks:
  argument-count:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 2000
  return-statements:
      config:
        threshold: 6

ratings:
   paths:
   - "**.js"
   - "**.py"
   - "**.md"
