os:
- linux
sudo: false
language: python
python:
- "3.6"
install: pip install tox-travis
script: tox

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE DATABASE travis_test_db;" -U postgres
  - psql -c "CREATE USER test PASSWORD 'pass';" -U postgres
  - psql -c "ALTER USER test CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE travis_test_db to test;" -U postgres


after_success:
  - coveralls
  - codecov
