# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('self_evaluation', models.PositiveSmallIntegerField(choices=[(0, 'wrong'), (1, 'sort-of'), (2, 'correct')])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'mixed'), (1, 'subsets only'), (2, 'questions only')], default=1)),
                ('for_any_authenticated', models.BooleanField(db_index=True, default=False)),
                ('for_unauthenticated', models.BooleanField(db_index=True, default=False)),
                ('show_authors', models.BooleanField(default=True)),
                ('own_questions_only', models.BooleanField(default=False)),
                ('questions_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True)),
                ('answer_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('blooms_tag', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'remember'), (1, 'understand'), (2, 'apply'), (3, 'analyze'), (4, 'evaluate'), (5, 'create')], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(-1, 'vote down'), (1, 'vote up')], db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askup.Question')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('qset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='askup.Qset')),
            ],
            bases=('askup.qset',),
        ),
        migrations.AddField(
            model_name='question',
            name='qset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askup.Qset'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(db_column='author_id', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qset',
            name='parent_qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='askup.Qset'),
        ),
        migrations.AddField(
            model_name='qset',
            name='users',
            field=models.ManyToManyField(blank=True, db_index=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askup.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('question', 'voter')]),
        ),
        migrations.AlterUniqueTogether(
            name='qset',
            unique_together=set([('parent_qset', 'name')]),
        ),
        migrations.AddField(
            model_name='emailpattern',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='askup.Organization'),
        ),
    ]
