# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='vote_value',
            field=models.IntegerField(default=0),
        ),
    ]
