# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askup', '0002_auto_20180227_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(),
        ),
    ]
