# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askup', '0003_auto_20180316_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='QsetUserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qset', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='askup.Qset')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject User Subscription',
                'verbose_name_plural': 'Subject User Subscriptions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='qsetusersubscription',
            unique_together=set([('qset', 'user')]),
        ),
    ]
