# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askup', '0004_auto_20180703_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set([('organization', 'name')]),
        ),
    ]
