version: '3.4'
services:
  postgres:
    image: postgres:10.1
    restart: $RESTARTPOLICY
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: askup
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  django:
    build:
      context: ..
      dockerfile: .dc-prod/django/Dockerfile
    restart: $RESTARTPOLICY
    stdin_open: $STDINOPEN
    environment:
      ASKUPENV: $ASKUPENV
      DJANGO_SETTINGS_MODULE: config.settings.$ASKUPENV
      PGPASSWORD: pass
      LOADMOCKUPDATA: $LOADMOCKUPDATA
    volumes:
      - ./.volumes/askup/log:/var/log
      - ..:/askup
    depends_on:
      - postgres
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  nginx:
    image: nginx:1.9.12
    depends_on:
      - django
    restart: $RESTARTPOLICY
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../askup/static:/var/www/sites/static
      - ./.volumes/nginx/logs:/var/logs
      - ./.volumes/nginx/tmp:/tmp
      - ./nginx/conf.d:/etc/nginx/conf.d
    logging:
      options:
        max-size: "10m"
        max-file: "10"
