version: '3.4'
services:
  postgres:
    image: postgres:10.1
    restart: always
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDBNAME
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data
  postfix:
    image: khaimovmr/postfix
    restart: always
    environment:
      MYHOSTNAME: $MYHOSTNAME
      myhostname: $MYHOSTNAME
    volumes:
      - ./.volumes/postfix/log:/var/log
  django:
    build: 
      context: ..
      dockerfile: .dc-prod/django/Dockerfile
    restart: always
    environment:
      PGPASSWORD: $PGPASSWORD
      MOCKUPDATA: $MOCKUPDATA # set to any non-empty string if the app should be filled with the mockup data
    volumes:
      - /opt/docker-volumes/askup/askup/log:/var/log
      - ../askup/static:/askup/askup/static
    depends_on:
      - postgres
      - postfix
  nginx:
    image: nginx:1.9.12
    depends_on:
      - django
    ports:
      - 80:80
    volumes:
      - ../askup/static:/var/www/sites/static
      - ./.volumes/nginx/logs:/var/logs
      - ./.volumes/nginx/tmp:/tmp
      - ./nginx/conf.d:/etc/nginx/conf.d
