version: '3.4'
services:
  postgres:
    image: postgres:10.1
    restart: $RESTARTPOLICY
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: askup
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  django:
    build:
      context: ..
      dockerfile: .dc-prod/django/Dockerfile
    restart: $RESTARTPOLICY
    stdin_open: $STDINOPEN
    env_file: .django.env
    volumes:
      - ./.volumes/askup/log:/var/log
      - ..:/askup
    depends_on:
      - postgres
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  celery_worker:
    image: $DJANGO_IMAGE_NAME
    command: bash -c "sleep 15 && celery -A askup worker -l info"
    env_file: .django.env
    volumes:
      - ./.volumes/celery_worker/log:/var/log
      - ..:/askup
    depends_on:
      - rabbitmq
      - django
  celery_beat:
    image: $DJANGO_IMAGE_NAME
    command: bash -c "sleep 15 && celery -A askup beat -l info --pidfile /var/run/celerybeat.pid"
    env_file: .django.env
    volumes:
      - ./.volumes/askup/log:/var/log
      - ..:/askup
    depends_on:
      - rabbitmq
      - django
  rabbitmq:
    image: rabbitmq
    env_file: .rabbit.env
  nginx:
    image: nginx:1.9.12
    depends_on:
      - django
    restart: $RESTARTPOLICY
    ports:
      - 8000:80
    volumes:
      - ../askup/static:/var/www/sites/static
      - ./.volumes/nginx/logs:/var/logs
      - ./.volumes/nginx/tmp:/tmp
      - ./nginx/conf.d:/etc/nginx/conf.d
    logging:
      options:
        max-size: "10m"
        max-file: "10"
